name: mixter
description: Mixter App

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^13.2.4
  intl: ^0.18.1
  mixter_bloc:
    path: packages/mixter_bloc
  mixter_supabase:
    path: packages/mixter_supabase
  mixter_ui:
    path: packages/mixter_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^5.3.0
  very_good_analysis: ^5.1.0

flutter:
  generate: true
