name: mixter
description: Mixter App

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_highlighter: ^0.1.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.1
  flutter_web_plugins:
    sdk: flutter
  go_router: ^13.2.4
  google_fonts: ^6.2.1
  intl: ^0.18.1
  ionicons: ^0.2.2
  markdown: ^7.2.2
  mixter_ai:
    path: packages/mixter_ai
  mixter_bloc:
    path: packages/mixter_bloc
  mixter_hive:
    path: packages/mixter_hive
  mixter_supabase:
    path: packages/mixter_supabase
  mixter_ui:
    path: packages/mixter_ui
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  melos: ^5.3.0
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  assets:
    - assets/images/

flutter_launcher_icons:
  image_path: "logo.png"
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21
  web:
    generate: true
    image_path: "logo.png"
    background_color: "#161718"
    theme_color: "#F6671A"
  macos:
    generate: true
    image_path: "logo.png"

flutter_gen:
  output: lib/app/assets
  line_length: 80
