name: mixter_bloc
description: Mixter Bloc
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.3

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^5.1.0
dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
