name: mixter_agent
description: Mixter agent.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.3

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  langchain: ^0.5.0+1
  langchain_openai: ^0.5.0+1

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  test: ^1.24.0
  very_good_analysis: ^5.1.0
