name: mixter_hive
description: Mixter Hive Database
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  mixter_bloc:
    path: ../mixter_bloc

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  very_good_analysis: ^5.1.0
